image: "rust:latest"

test:cargo:
  tags:
    - akita
  before_script:
    - rustc --version && cargo --version
    - sed -i "s/ssh:\/\/git/https:\/\/gitlab-ci-token:${CI_JOB_TOKEN}/" Cargo.toml
    - sed -i 's/\.git//' Cargo.toml
  script:
    - cargo install cargo-tarpaulin --vers "^0.18"
    - RUST_LOG=warn cargo tarpaulin --out Xml --verbose
  artifacts:
    reports:
      cobertura: coverage.xml
