[package]
name = "s2gpp"
version = "0.1.0"
authors = ["wenig <info@pwenig.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.8"

actix = "0.10"
ndarray = "0.15.1"
csv = "1.1.6"
ndarray-csv = "0.5.1"
kdtree = "0.6.0"
num-traits = "0.2.14"
sortedvec = "0.5.0"
