[package]
name = "s2gpp"
version = "0.1.0"
authors = ["wenig <info@pwenig.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.8"
structopt = "0.3"

actix = "0.10"
actix-telepathy = "0.1.1"
actix-broker = "0.3.1"
serde = "1.0"
ndarray = { version = "0.14", features = ["serde"] }
ndarray-linalg = { version = "0.13",  features = ["openblas-static"] }
ndarray_einsum_beta = "0.7.0"
csv = "1.1.6"
kdtree = "0.6.0"
num-traits = "0.2.14"
num-integer = "0.1.44"
sortedvec = "0.5.0"
