[package]
name = "s2gpp"
version = "0.1.0"
authors = ["wenig <info@pwenig.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
actix-rt = "1.1"
port_scanner = "0.1.5"
rayon = "1.5.0"
plotters = "0.3.1"

[dependencies]
log = "0.4"
env_logger = "0.8"
structopt = "0.3"
indicatif = "0.16.2"
console = "0.14.1"

actix = "0.10"
actix-telepathy = "0.1.2"
actix-broker = "0.3.1"
serde = "1.0"
serde_with = "1.9.1"
ndarray = { version = "0.14", features = ["serde"] }
ndarray-linalg = { version = "0.13",  features = ["openblas-static"] }
ndarray_einsum_beta = "0.7.0"
ndarray-stats = "0.4"
csv = "1.1.6"
kdtree = "0.6.0"
num-traits = "0.2.14"
num-integer = "0.1.44"
sortedvec = "0.5.0"
petgraph = "0.6.0"
anyhow = "1.0.41"

meanshift-rs = { git = "ssh://git@gitlab.hpi.de/phillip.wenig/meanshift-rs.git", tag = "0.2.5" }
